### ISSUE TITLE
Harvest Report in Barn Kit Tab

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#136]
See Harvest -> Report in the original FarmData at [https://farmdata.dickinson.edu/guest.php](https://farmdata.dickinson.edu/guest.php)

User friendly query for harvest data.    Choose date range, field and crop, get harvest data for that   period.  ALL is allowed value for field   and crop to provide summary data, or drill down into specific fields.  Data report includes total yield expressed   in the default harvest unit for crop selected (FD converts harvest data   inputs from a variety of units to crop default unit, based on unit conversion   table).    Report also shows   "yield per row foot" which is calculated by dividing total yield   for the period by total row feet planted (from transplant or direct seed   tables) for that crop in selected fields over the same period.   Report includes labor data in units per   labor hour

**Comment by Batese2001** [comment]
Currently as merged with main according to pull request #155:
- When one visits the harvest report tab, one is able to type a title, select a date range (the default of which is from the start of the current year to the current date), field and crop from the database. 
- All is an allowed value for both crop and field. 
- Results are produced when one clicks the generate report button. 
- Each harvest log in the report contains the date it was harvested, the crop, the field, the individual yield in the given unit, the worker who inputted the log, and a semi-functional delete button. 
- Below this table there is a yield table that consists of all the crops alongside their respective total yields. 

With the addition of pull request #158:
- Below this table is a download link that converts the two tables into one csv file containing all of the data, which can be downloaded and named after the inputted title. 

Problems:

1. The fields and crops in the dropdown are found directly in the database. However, if it is entered incorrectly or is not updated in an input form and thus makes its way into the log database, then it cannot be filtered to by the selection and will only be accessible via the ALL option. Thus there should be a way of preventing this or otherwise updating the database to include these other options.

2. Some logs do not have necessary information such as a harvest unit or a crop name. This makes the code crash. This should be handled or otherwise prevented higher up. 

3. Results are limited to 100 logs for each search due to the limitations of the request. In the data returned by the request, there is information including the current result page, the first and the last, as well as the next. This should be used to create a bigger and more accurate table if a result could be more than 100 logs. 

4. Crops occasionally are inputted with different units, causing them to be unable to be added together accurately. In this code, it adds them separately but I am unsure if this is the desired result. 

5. The delete button does not update the database and instead only updates the lists on the page, giving the correct appearance but leaving this as a potential error when others wish to get the same report. 

6. The csv download link is for both tables. If two separate files are desired or only one type is needed, there is no way to do this with the current code. This could be an unnecessary fix, depending on stylistic choice. 

7.  There is no way to get labor data in the current database, thus it is impossible to give labor hours.

8. With a long response time, sometimes the harvest report will display "There are no matching records." even when there are or rather will be when the results load. It would be good to include a results loading message to let the user know that there could be results, but just not yet.

**Comment by amelia291** [comment]
Unfinished Story: Yield Per Row Foot
Problem: 
- I'm having a problem with getting the correct row foot of the current yield because I'm unsure of the relationship between them (i.e how they are connected - with id, name, etc)

Overall problem: 
- The API documentation is not very detailed, so it might be hard to navigate and get the necessary data. The data format is also not uniform.
-> We should include error checks for the format of the input and also some default values if the user doesn't provide input. 
 
- Some data appear in one API endpoint but not in others. For example, many fields are not included in the planting endpoint but still show up in the harvest log → This can cause important information to be left out.

**Comment by braughtg** [comment]
Closing as the course is now complete.  A new issue will be created for the completion of this feature.
