### ISSUE TITLE
Seeding Report Testing Failures with 403 Responses

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#295]
The cypress tests for the seeing report (farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js) fail intermittently with 403 responses.  To see this run the tests from the farmdata2_modules directory with the command: ./testRunner.bash e2e and choose the seedingReport.spec.js tests.  Because the failures are intermittent it may take several runs to experience a failure and failures may occurs in different tests. 

Note that all of the tests pass when run individually.  So the functionality is correct and is being tested correctly.  However, there are issues with the login failing when the tests are automatically run in sequent. 

This seems to be due to login/logout issues with the beforeEach clauses for the describe and context blocks in the tests.  For example:

![image](https://user-images.githubusercontent.com/16962482/136796078-daeae7fc-ab67-4c97-9d32-fe5ef38e271d.png)

Some research and experimentation should be done to verify what is causing the issues and resolve them.

**Comment by braughtg** [comment]
See tests for the API sub tab of the FD2 Example (farmdata2_modules/fd2_tabs/fd2_example/api.spec.js) for an example of how to structure the tests to avoid these 403 errors. In particular, see the beforeEach hook and how it waits for page content to be loaded in the Vue mounted hook. Following that model should fix these issues.

**Comment by braughtg** [comment]
Superseded by #367.

**Comment by FutzMonitor** [comment]
This is currently still an ongoing issue when running the tests in sequence. As you mentioned in the original posting, the tests run fine individually and pass without any problem but once they are run in sequence there is the possibility of experiencing an error 403. It's the same behavior: sometimes it occurs and sometimes it does not, it can occur in random tests, and it continues to be the same error 403 that triggers this failure. I will look into it because this a bug that should not occur. Ideally the tests can be run sequentially from start to finish without this error which aborts all testing.
