### ISSUE TITLE
Add Harvest Input Log to the Field Kit

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#417]
Plantings that exist in a field can be harvested.

The functionality of the FarmData2 Harvest Input Form will be similar to the Harvest Input Form in the original FarmData, which can be seen here: 
* https://farmdata.dickinson.edu/Harvest/harvest.php?tab=harvest:harvestInput

Notes:
* The original farm data allowed a harvest log to have multiple fields associated with it.  This represented a harvest that picked the crop from multiple distinct locations.  In FarmData2 harvests from separate locations will need to be created as separate Harvest Logs.

In FarmData2 this Harvest Input Form will appear in the Field Kit tab and will allow the user to create a log that records a harvesting.  When creating this form, the style and user experience should be similar to:
* The examples that appear in the FD2 Example tabs
  * Their defining code is in the html files in the directory: farmdata2_modules/fd2_tabs/fd2_example
* The Seeding Input form that appears in the Field Kit.
  * Its defining code is in the file: farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html

Data Model Notes: 
* All Harvest Logs must have a Planting Asset associated with them.
  * The Planting Asset represents the crop that is currently planted and is being harvested.
* Only Planting Assets that are currently located in a field are eligible to be transplanted.
* The creation of a new Harvest Log represents the action of picking the crop.

Information about Harvest Logs and Planting Assets:
* General documentation for the sample database: https://github.com/DickinsonCollege/FarmData2/tree/main/docker/sampleDB
  * API Calls in that document show how to retrieve existing logs and assets that can be used to understand the JSON structures and their contents.
* The JSON Structures used to create the Logs and Assets in the sample database can be found in the python files in the docker/sampleDB directory:
  * The JSON structure for a Harvest Log and the process of creating one can be found in the file: docker/sampleDB/addHarvests.py
  * The JSON structure for a Planting Log can be found in the file: docker/sampleDB/addDirectSeeding.py
* Information about the API calls used to create Logs and Assets using the JSON structures can be found:
  * In the file: docker/sampleDB/utils.py
  * In section of CONTRIBUTING.md that points to the FarmOS API documentation.

**Comment by johnmaccormick** [comment]
If you get a login error at the first link above, you need to first visit [https://farmdata.dickinson.edu/guest.php](https://farmdata.dickinson.edu/guest.php) to log in as a guest.

**Comment by goldberl** [comment]
**Should the Harvest Input form record the area of the harvest in the log table?** 

We have a dropdown for the area in the actual form, but it is currently not being recorded on the log under the 'areas' column header.

We are trying to stay consistent with how the seeding logs are displayed. However, the seeding logs do not have their areas recorded, but past harvest logs do show their areas being recorded. Please view the screenshots below for clarity:

Current harvest log record (no area is recorded)
![image](https://user-images.githubusercontent.com/76408777/165662164-a34edf52-3625-4018-aeea-f0b9ed3eee5b.png)

Current seeding log record (no area is recorded)
![image](https://user-images.githubusercontent.com/76408777/165662659-3a0c2edd-bfec-49ac-b700-d06ca7a0c082.png)

Past harvest log record (area is recorded)
![image](https://user-images.githubusercontent.com/76408777/165662257-7c0c8038-9275-4ebb-b86c-2979f7fa7533.png)

Also, just a note: when the SEEDING section is directly clicked from the LOGS dropdown on the top of the app, it shows slightly different column headers than if you just go to LOGS in general (with no filter). Here, the seeding logs have a column for 'value', 'units', and 'movement to' (which I assume is the same as the 'areas'). 

Seeding logs directly from LOGS dropdown (area is recorded)
![image](https://user-images.githubusercontent.com/76408777/165663062-aaa92ab5-5987-4ae5-a9dd-3ece2b1b1686.png)

The harvest logs are also slightly different if you click the HARVEST section from the LOGS dropdown. Here, 'area' is listed instead of 'movement to', and the order of the columns are different

Current Harvest logs directly from LOGS dropdown (area is not recorded but past harvest logs (not in screenshot) do have area recorded)
![image](https://user-images.githubusercontent.com/76408777/165663316-e33038e1-f5e5-4354-a7af-f9079873e3fa.png)

This is another issue all together, but should these records (the column headers) be consistent with each other no matter how you get to the logs?

**Comment by goldberl** [comment]
Also does anyone have suggestions on how we can limit the crop dropdown list to only display crops that are currently planted? 

I realized we probably have another problem that we will have to solve before figuring this out. Right now, I think we are creating new Planting Assets with each harvest (feature brought over from the code of the seeding input form). Is that a reasonable understanding of what may be happening? And is it correct to say that we have to use API calls to retrieve existing planting assets, and this will help us filter the crop dropdown?

**Comment by braughtg** [comment]
> Should the Harvest Input form record the area of the harvest in the log table?

The images that you are showing here are displaying the logs using the FarmOS interface.  The FarmData2 interface (i.e. the sub-tab in the BarnKit) should display a table similar to the one in the Seeding Report.  That table should contain columns for all of the same data that is reported in the original FarmData application.

**Comment by braughtg** [comment]
> Also does anyone have suggestions on how we can limit the crop dropdown list to only display crops that are currently planted?

The harvest input form will need to use the existing planting assets to know what crops are in the ground and where they are located.  Given that information, you can use computed properties for the dropdowns, similar to what is done in the seeding log and report pages to customize those lists to what plantings are actually available for harvest.

**Comment by goldberl** [comment]
I think I've figured out how to limit the crop drop down. 

![image](https://user-images.githubusercontent.com/76408777/168395823-a2cd58ad-8564-49e8-b8b8-82f988b63125.png)

However, when I hit the submit button, it says that the log has been recorded, but I cannot find the log in the 'Logs' section of the app. I am not sure how to fix this.

Also, now that the crop dropdown is populated with planting assets, do we need a dropdown for 'Area' since the planting asset has the area in it?

**Comment by braughtg** [comment]
> However, when I hit the submit button, it says that the log has been recorded, but I cannot find the log in the 'Logs' section of the app. I am not sure how to fix this.

Sounds like maybe the log is not being created if you cannot find it. One thing to do would be to open the Network pane of the Dev Tools in the browser and then make the request to create the log. Then you’ll be able to see the request being sent and the response that you get back. That will let you confirm if the log is being created or if there was an error.

**Comment by braughtg** [comment]
> Also, now that the crop dropdown is populated with planting assets, do we need a dropdown for 'Area' since the planting asset has the area in it?

It looks like you’ve populated the crop drop down with the log name and not just the crop. That drop down should just have the crops names in it. You can use the crop ids in the logs and the idToCrop map to get the names. Have a look at the seeding report for an example of how this is done.

**Comment by goldberl** [comment]
**Current Status of Issue (as of 5/17/2022):**
There exists a text field for everything that the user should record for a Harvest Log. This includes the date, crop, area, units, yield, comments, workers, and time of a harvest.
![image](https://user-images.githubusercontent.com/76408777/168870664-1785fe87-e107-4ebe-8a6d-e94c15acef73.png)

**Date:** Users can pick any date. 
- Future dates should be disabled (this is not implemented)

**Crop:** Users can pick any crop. 
- This should be limited with an API call to crops that can be harvested. To do this we tried to change the endpoints in the ‘created’ section from `/taxonomy_term.json?bundle=farm_crops` to `/farm_asset.json?type=planting`. This may have limited the dropdown, but logs are not being properly recorded and this error occurs:
![image](https://user-images.githubusercontent.com/76408777/168869917-1296d0ac-fbe7-4779-b0c9-b650b5976e10.png)
- By changing the endpoint, the entire name of the planting asset shows up. Only the name of the crop should show up. To try and fix this, this code was added to the ‘computed’ section, and the function of the dropdown connected to the crop selection was changed from ‘cropArray’ to ‘cropList’. However this did not solve the issue. The page renders correctly but now nothing is populating the crop dropdown.
![image](https://user-images.githubusercontent.com/76408777/168869970-bf994209-2878-4c1d-9ca4-850c5978a856.png)


**Area:** Users can pick any area
- This may also have to be limited to the areas that the selected crop can come from (not implemented)

**Yield & Units:** Users can type in a number and select a unit from a drop down
- Yield is recorded correctly
- Yield should not allow users to enter invalid numbers (not implemented)
- Units are not being recorded correctly. Right now, a set value of ‘POUNDS’ is recorded for every harvest.
- To fix this, we tried using `this.unitToIDMap.get(‘???’)`, but we were not quite sure what value to get. This code is in the `quantityHarvest()` function in the ‘computed’ section

**Comments**: Users can type comments, this is optional
- Everything seems to be working fine with the comments

**Workers/Time**: Users can type the number of workers and the time of a harvest
- Everything seems to be working fine with these fields
- These fields should not allow users to enter invalid numbers (not implemented)

**Summary of future work & challenges:**
* Major/Important challenges
   * Get the units properly recorded
   *   Limit crop drop down with API call to plants that can be harvested (and show just the names of the crops)
* Minor challenges:
   * Disable future dates on date picker 
   * Do not allow user to enter negative numbers for yield, worker numbers, and time

**Comment by braughtg** [comment]
Closed as the course associated with this issue has concluded.  It will be preserved in the project history as a basis for implementation of this feature in the future.
