### ISSUE TITLE
Seeding Report Summary Labor Data Calculation after Hidden/Optional Labor Configuration

### ISSUE THREAD

**Issue by JingyuMarcelLee** [DickinsonCollege/FarmData2#536]
## Description of the Issue 

After allowing users to make configuration changes to hide the display of labor-related fields on both seeding input form and the seeding report (Issue #520 #519 covered by #515) , a new problem has arisen. When the logs without labor data created with "hidden" or "optional" labor configuration are displayed in the seeding report, the report automatically converts the N/A values to 0, using this in the calculation of the data summary on the summer table at the bottom of the page.

## Steps to Reproduce
![1](https://user-images.githubusercontent.com/46755208/179082104-8cdd5bbe-2c7a-42aa-a07f-a6ff82b99fc5.png)

1. Go to the configuration page and change the setting to Hidden or Optional. Save the change.

![2](https://user-images.githubusercontent.com/46755208/179082108-4f23dcaf-23fb-4775-a8a4-fb2346341509.png)

2. Go to the Seeding Input log and create a log without the labor data (leaving it blank)

![3](https://user-images.githubusercontent.com/46755208/179082109-a07fe3c3-46bb-467a-a7a2-64fca9c090e2.png)

3. Go back to the configuration page and set the labor back to required (so you can see labor-related data on the report)

![4](https://user-images.githubusercontent.com/46755208/179082111-d9fd5912-921d-4e8d-ae6d-03bc82b8ae79.png)

4. Visit Seeding report and enter today's date. Generate the report. The labor data shows 0 instead of N/A. The summary table uses this value to make calculations for total and average hours. 

![5](https://user-images.githubusercontent.com/46755208/179082115-26a65272-8b89-4bbf-9e66-7e17ece166e3.png)

5. The actual log has N/A for number of workers and hours. 

## Suggested Solution
Fix the computed properties in the seeding report so that N/A values are excluded in its calculation. Before that, we need to check if the JSON for the seeding log actually saves an empty value as 0 by default. If this is the case, this has to be addressed in the seeding input so that empty values do not get saved as 0.

**Comment by braughtg** [comment]
Nicely described.  I agree that the computed properties will need to account for the N/A values and ensure that we don't get division by 0 or other incorrect computations of the totals and averages when some logs have labor and others do not.

My sense is that we should just omit any log that does not have labor from the computation of the averages.  This may mean that there will be different totals used for the total and the averages because all records can be used in the total, but only those with labor information can be used in the total that is used to find the average.

**Comment by JingyuMarcelLee** [comment]
I will work on this
