### ISSUE TITLE
BarnKit Seeding Report Default for Seeding Type Filter

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FarmData2#658]
Currently when a Seeding Report is generated the Seeding Type displayed defaults to "All" even if there are no Direct Seedings or Tray Seedings.  Would it be more useful to have the report automatically detect what types of seedings actually appear in the report and then default to Direct Seedings, Tray Seedings or All?

**Comment by FutzMonitor** [comment]
Depending on what option is selected in the "Seeding type" filter the look of the table defaults to three different views: 
1. When **ALL** is selected - A general view that omits specific data relating to direct and tray seedings.
2. When **Direct Seeding** is selected - A filtered view of only direct seedings with additional information for those types of seedings.
3. When **Tray Seeding** is selected -- A filtered view of only tray seedings with additional information for those types of seedings. 

I think it would be best for the user if the table could detect if there is only one type of seeding within that date range and to select that view for the user by default. For example, in the below image there are only direct seedings: 
![image](https://github.com/DickinsonCollege/FarmData2/assets/31524934/f821665a-36b6-4e6f-99bc-d3263cf1be93)

It is unnecessary to display the tray seeding summary table and additional information about the direct seeding logs are hidden from the user because the **ALL** option is selected. 

In my opinion, it would be more beneficial for the user to arrive at this view by default in this situation: 
![image](https://github.com/DickinsonCollege/FarmData2/assets/31524934/8f49b07f-d4b7-40f2-8285-c67b50b74c66)

It saves a click, and it immediately displays all information present when only one seeding type appears.

**Comment by Mikek16** [comment]
This issue seems like it would be a good first or second issue, however if we don't want to reserve it I have a fix in mind and would like to work on this issue.

**Comment by braughtg** [comment]
Super.  I've assigned the issue to you.  Get back in touch here if you have questions.

**Comment by Mikek16** [comment]
@braughtg pr #680 is ready for review, let me know if there are any necessary changes.
