### ISSUE TITLE
Migrating Pull Requests from 2023 FD2School Repo

### ISSUE THREAD

**Issue by RolandLocke** [DickinsonCollege/FarmData2#660]
Pull requests completed in the [2022-23 FD2School](https://github.com/DickinsonCollege/FD2School-FarmData2) repo, should be merged to this repo.

History of the the commits behind each pull request information must be included in this process to preserve both authorship and details on the work completed.

**Comment by Foogabob** [comment]
Merging pull requests without common history can be achieved by passing the --allow-unrelated-histories flag with the merge command. File conflicts will still be flagged for manual resolution.

**Comment by braughtg** [comment]
The commits in the FD2School Repo will have a common history with the main FD2 repo because FD2School was a fork from the main repo.  So that shouldn't be an issue.  I think that the main challenge will be for each commit that was merged into FD2School to get it into a PR to the main repo.  I haven't done this, but I think the process will be to:

* Make a fork and clone of FD2School
* In your clone set an upstream to the main FD2 repo
* Then for each PR that was merged into FD2School one-by-one
  * Make a branch in your clone
  * Use `git cherry-pick` to pull the commit from that PR into your new branch
  * Make a PR for that branch to the main FD2 repo.
    * Use a title for the new PR that is:  Migrates: <original title>
    * Include in the body of the new PR a link to the original PR and the original Issue.  
  * Resolve any merge conflicts (though I don't expect many if any due to the way the project is structured.)
  * Repeat for each PR in FD2School.

Note: Each of the PR in FD2School were "Squash Merged" so there should only be one commit per PR.

**Comment by Foogabob** [comment]
@braughtg FD2School already has all the PR's. I couldn't figure out a way to cherry-pick them from that fork directly to the main project in the way described above.

Instead what I've done is:
- create a new fork and clone of the main FD2 project, with upstream to the main FD2 repo
- add FD2 school as a remote to the clone
- call a fetch command to that remote. This populated the working directory with all the commits that were made in FD2School.
Next thigs to figure out are:
- cherry-pick those commits FD2School commits into branches on the FD2 main clone
- create pull requests to the main issue

let me know if you can see any issues with this method.

**Comment by braughtg** [comment]
Nice work.  This sounds like a reasonable approach to me.  You'll just want to be careful that when you fetch from the FD2School remote that you are doing so in a branch in your clone so that you keep main in synch with the upstream FD2.

You should be able to find the commit hashes in the merged PRs in the FD2School repo.

**Comment by Foogabob** [comment]
In order to properly add users as co-authors you must include their emails in the co-author section. This will ensure that git blame will work in the future.

To locate a users email, which is usually not listed in a users profile, follow [this ](https://www.nymeria.io/blog/how-to-manually-find-email-addresses-for-github-users) guide.

**Comment by Foogabob** [comment]
Issue that lists the progress of this ticket: https://github.com/DickinsonCollege/FarmData2/issues/662

**Comment by braughtg** [comment]
@RolandLocke Thanks for your work on this!  I have now merged all of these PR's.  You can see them in the history and that everyone that made commits is correctly attributed.  Nicely done!

**Comment by RolandLocke** [comment]
@braughtg Of course, I'm glad that everyone's work made it into the project!
