### ISSUE TITLE
sudo docker-compose up -d returns error

### ISSUE THREAD

**Issue by brunokaboyi** [DickinsonCollege/FarmData2#69]
An unexpected error:
![error after running sudo docker-compose up -d](https://user-images.githubusercontent.com/42941446/102450394-482eb700-4004-11eb-8aff-3f12c8d2855f.PNG)
was returned after running the command sudo docker-compose up -d. I am not sure if the issue was caused because of my personal machine but I was able to fix it by running this command `sudo systemctl stop apache2`

**Comment by braughtg** [comment]
This happens when there is a copy of apache running already, stopping it as suggested works.  It would be good to add this to he install doc as a "quick fix" or "common issue" so that others can resolve it. 

The docker-compose up -d command should not be sudo, so need to check install so that it is not that way.

**Comment by braughtg** [comment]
Currently working on a new install process and will make this update when I update the INSTALL.md document.
